version: '3.8'
services:
  #  gateway:
  #    build:
  #    image:
  #    container_name:
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #    environment:
  #      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: Dockerfile
    image: server_image
    container_name: server_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8080
      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - DB_NAME=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15.4-alpine
    #    container_name:
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root