server:
  port: 8080

logging:
  level:
    org:
      springframework:
        orm.jpa: INFO
        transaction: INFO
        transaction.interceptor: TRACE
        orm.jpa.JpaTransactionManager: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:./db/shareit
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always










